name: Java CI with Gradle

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4.4.0
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pull-request-build
        path: build/libs/

